hometasks 1-3
askar12345678/python pull request #3
Opened 2022-09-27 17:06 UTC by askar12345678

2022-10-04 15:27 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "len_old = len(old)\n",
Не уверен, что стоило ради хранения длины переменную заводить)

2022-10-04 15:27 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "old = [i for i in s.split()]\n",
Непонятное имя `old` (что старое?)

2022-10-04 15:32 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "ind, ind1, ind2, ind3, ind4, ind5 = [], [], [], [], [], []\n",
Сама по себе эта строчка уже "вызывает вопросы") Пять похожих списков... Выглядит как что-то "неоправданно сложное", и с чем далее сложно будет работать...

2022-10-04 15:33 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "ind, ind1, ind2, ind3, ind4, ind5 = [], [], [], [], [], []\n",
Имена `ind` не очень понятные) Тогда уж лучше было `inds` назвать (чтоб множественное число было видно).

2022-10-04 15:33 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "ind, ind1, ind2, ind3, ind4, ind5 = [], [], [], [], [], []\n",
Ну, и да, пока не понятно, почему их вообще именно пять штук.

2022-10-04 15:39 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "        if old[i] == 'Джек' and old[i+1].find('Воробей') == 0:\n",
`old[i+1].find('Воробей') == 0` — сложно) Почти как из серии "чесать за ухом ногой вместо руки". Почему нельзя было сделать просто:
```python
old[i+1] == 'Воробей'
```
...Ааа, знак препинания? Ок, ладно, но есть ещё, по-моему, неплохой вариант:
```python
old[i+1].startswith('Воробей')
```
(но вообще и такой вариант, и ваш исходный неправильно обработали бы строчку типа "Джек Воробейник")

2022-10-04 15:41 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "        if old[i] == 'Джека' and old[i+1].find('Воробья') == 0:\n",
Много почти похожего кода. Не очень хорошо) А если бы было 20 падежей? :sweat_smile: А если вместо Джека Воробья захочется ещё кого-нибудь исправлять? Плюс при таком почтипереписывании очень просто где-то совершить ошибку, которую потом будет очень сложно найти.

2022-10-04 15:43 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "new = old.copy()\n",
Ок. Но стоит понимать, что это будет shallow copy (если бы был список списков, то внутренние бы были "разделены" между копиями).

2022-10-04 15:45 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "ind = [ind1] + [ind2] + [ind3] + [ind4] +[ind5]\n",
А зачем вы тогда десять строчек выше `ind` ввели, если он оказывается только здесь задаётся?)

2022-10-04 15:48 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "dict_= ['капитан'] + ['капитана'] + ['капитану'] + ['капитаном'] + ['капитане']\n",
Имя:
* непонятное по смыслу (что тут лежит в переменной)
* плюс это вообще не словарь
* черта на конце "вызывает подозрения" (так обычно не именуют, и "возникают вопросы", зачем так надо было делать)

2022-10-04 15:51 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "dict_= ['капитан'] + ['капитана'] + ['капитану'] + ['капитаном'] + ['капитане']\n",
Кажется, должен быть важен порядок "капитанов", но из кода это как бы не очевидно... Результат работы программы зависит от порядка слагаемых в некоторой строчке... Понимать сложно, сломать просто, самому где-то в процессе ошибиться тоже не сложно)

Если "Джеки" связаны с "Капитанами", то стоило бы эту связь как-то более явно обозначить. Например, как раз через словарь. Где бы "Джек", например, отображался бы в нужного "Капитана".

2022-10-04 15:52 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "for k in range(0,5):\n",
"Магическая" пятёрка: смотришь на эту строчку саму по себе, и ничего не понятно, что за "пять".

2022-10-04 15:53 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "    cnt = 0\n",
`cnt`?) Типа `count`? Не уверен, что такое сокращение как-то оправдано)

2022-10-04 15:54 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "        cnt+=1\n",
Нет пробелов до-после `+=`

2022-10-04 15:55 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "    print(i, end =' ')\n"
Самый последний `print` тоже строчку не переводит (а, кажется, должен бы).

2022-10-04 17:03 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "    while cnt != l[k]:\n",
По-моему, этот цикл while — просто "завуалированный for". (Если понятно, что итераций будет конкретное число, то лучше использовать for вместо while.)

2022-10-04 17:13 UTC, Alvant reviewed
Ок! Кажется, по первой задаче можно (и имеет смысл) поправить пару вещей:
* причесать проверки вида `old[i+1].find('Воробей')`, чтобы "Воробейников" не прошёл (видимо, надо просто как-то отсечь знаки препинания на конце, и сделать проверку на равенство)
* и сделать так, чтобы самый последний print всё-таки печатал с переносом строки (без `end=' '`)

2022-10-04 18:51 UTC, Alvant reviewed
Второе задание — Ок. Но стоит поправить:
* объявление переменной `x` перенести вниз, туда, где она будет нужна
* убрать `/tmp` из команды `df . -h /tmp`? (либо я не понял, что тут происходит :sweat_smile:)

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +x=$(find . -not -path '*/.*' -type f | wc -l)
`find . -not -path` — убираете файлы в скрытых папках?.. Ок. Пусть будет так)

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +x=$(find . -not -path '*/.*' -type f | wc -l)
Но что не совсем ОК — это то, что вы
* определяете переменную с непонятным именем
* и определяете её... "непонятно зачем", слишком рано — ведь понадобится она только в самом конце скрипта (определение в "нужном месте" облегчило бы понимание)

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +touch info.txt
По идее можно бы было и не трогать: `echo` далее сама создала бы файл.

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +echo "Hello, $USER" >> info.txt
То есть в файл info.txt всегда происходит дозапись? (При повторном вызове дозапишется в конец.) Ок. Пусть будет так) Но мне казалось, что лучше записывать файл с нуля при каждом вызове. (Чтоб как бы текущий срез информации показать, а не "развитие во времени".)

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +du -sh --apparent-size | awk '{print $1}' >> info.txt
`--apparent-size` — о, ни разу не видел такого) Ок :writing_hand:

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +df . -h /tmp | tail -1 | awk '{print $4}' >> info.txt
А что делает `/tmp`?..

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +echo $'\n' >> info.txt
Зачем именно две пустых строчки на конце в info.txt?)

2022-10-04 18:51 UTC, Alvant commented on labs/lab02/hw2.sh
> +#!/usr/bin/bash
После строчки с шебангом можно бы было пустую строчку оставить в скрипте, чтоб визуально лучше отделялось.

2022-10-15 10:50 UTC, askar12345678 commented on labs/lab02/hw2.sh
> +x=$(find . -not -path '*/.*' -type f | wc -l)
x объявил перед созданием info.txt,чтобы info.txt не учитывался при подсчете файлов.я просто подумал при первом вызове не надо его самого считать.

2022-10-24 14:06 UTC, Alvant approved these changes
В первой задаче: похоже, история с Воробейником закончена, но теперь появился Вор-о-бей)

Вторая — ОК

2022-10-24 14:06 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "def puncdel(s):\n",
Имя не очень для функции. Так бы можно было библиотеку назвать, но не функцию) В данном случае "нормальным" именем для функции было бы `delete_punctuation`.

2022-10-24 14:06 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +    "import string\n",
После испортов принято две пустых строчки оставлять, до основного кода.

2022-10-24 14:06 UTC, Alvant commented on labs/lab01/hw1.ipynb
> +      "А я Джек Воробейник!\n",
Хорошо! Воробейника отсекли) Но... получается, теперь программа неправильно обработает, например, имена `"Джек В'оробей"` или `"Джек Вор-о-бей"`?)

2022-10-24 14:06 UTC, Alvant commented on labs/lab02/hw2.sh
> +x=$(find . -not -path '*/.*' -type f | wc -l)
@askar12345678 а, ок! Стоило бы тогда в скрипте коммент оставить, почему важно, чтобы эта строчка шла первой) А то, вот, было не очевидно. Ну, и, да, имя всё-таки стоило бы попонятнее дать переменной)

2022-10-24 14:06 UTC, Alvant commented on labs/lab02/hw2.sh
> +df . -h | tail -1 | awk '{print $4}' >> info.txt
Кстати, вместо `tail -1` ещё можно бы было `tail -n 1` сделать (https://stackoverflow.com/a/36989499/8094251).

2022-10-24 14:45 UTC, Alvant requested changes
По третьей лабе:
* стоит сделать так, чтобы и на Линукс, и на Виндоус путь до домашней папки можно бы было получить
* повставляйте пустые строчки для читаемости?) причешите словарь с фильмами, чтоб он выглядел красиво в коде?
* сделайте чисто через Питон создание-удаление папок, без Юпитера?
* в csv сейчас не то записывается вместо `8470-13447 and 8482-13459`
* в конце надо по-честному получить отсортированный список файлов)

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "import pickle\n",
Кажется, пикл не используется.

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "os.chdir(os.getenv(\"HOME\"))\n",
По-моему, на Windows такое не заработает... Можно ли получить путь до домашней папки так, чтобы и на Линуксе, и на Виндоусе код работал?

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "if os.path.exists('hw3') and os.path.isdir('hw3'):\n",
Сложно такую простыню читать) Используйте пустые строчки для разделения разных по смыслу действий, блоков. Например, перед if-else-ами стоит пустую строчку оставлять, перед циклами while/for.

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "    ! rm -r hw3\n",
Нечестно) Нет, давайте чисто на Питоне чтоб программа была?) Пусть в Юпитер-ноутбуке, но Питон.

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "if os.path.exists('hw3') and os.path.isdir('hw3'):\n",
Обязательно нужно две проверки?

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "    ! mkdir hw3\n",
Две строчки `mkdir` — можно бы было только один раз прописать.

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "        [\"Breast\",1,1,1,1,8470-13447 and 8482-13459,0,1],\n",
`8470-13447 and 8482-13459` — нет, тут получится что-то непонятное

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "    for x in data1:\n",
Снова `x`, снова за именем смысла вообще не видно) Тут намного лучше выглядело бы имя `row`.

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "with open(\"file.csv\", \"a\") as file:\n",
Почему append режим?

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "        ]\n",
Вот эту скобку лучше бы было влево переместить:
```python
data1 = [
    ["Cancer Type","D-Loop","mRNAs","tRNAs","rRNAs","Nucle ...
    ...
]
```

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "data = {'movies': [{'name': 'Полночь в Париже',\n",
Словарь "шатает" туда-сюда, читать сложно.

2022-10-24 14:45 UTC, Alvant commented on labs/lab03/hw3.ipynb
> +    "print('file.txt', 'file.json', 'file.csv')\n",
?) Не понял) Какой-то странный print) А, нет, нет. Тут смысл был в том, чтобы 1) *средствами Питона получить список файлов в папке* и 2) *средствами Питона отсортировать их* по времени создания. А в принте, как у вас, "обучающего элемента" вообще ведь никакого нет)

2022-11-03 10:16 UTC, Alvant commented on labs/lab01/hw1_x2modified.ipynb
> +    "    while flag != False:\n",
```python
while flag:
```

У вас тоже ОК, но немного "неуклюже")

2022-11-03 10:20 UTC, Alvant commented on labs/lab01/hw1_x2modified.ipynb
> +    "def delete_punctuation(s):\n",
Имя функции не вполне отражает суть. Это раньше она удаляла вообще всю пунктуацию. Но теперь — именно справа... То есть лучше бы было назвать, например, `delete_punctuation_right`... Или — `rstrip_punctuation`. В Питоне у строки есть метод `rstrip`. И вполне можно бы было назвать свой метод "по аналогии". И всем, кто пишет на Питоне, сразу стало бы понятно. Потому что, да, название `delete_punctuation_right` уже немного "сложным" получается)

2022-11-03 10:21 UTC, Alvant commented on labs/lab01/hw1_x2modified.ipynb
> +    "    for i in range(0, len(s)-p):\n",
Можно бы было сразу срез сделать, вместо цикла.

2022-11-03 10:22 UTC, Alvant commented on labs/lab01/hw1_x2modified.ipynb
> +}
Новый ноутбук можно было не делать. Лучше бы было исправление в старый внести.

2022-11-03 10:22 UTC, Alvant approved these changes
Первая задача — ОК

2022-12-09 20:37 UTC, Alvant approved these changes
Третье — Ок. Только из-за неразберихи в ветках у вас и шестое ДЗ тут же обновилось)

2023-05-23 01:25 UTC, merged